var selection = 0;
var index = 0;
var buffer = '';

// autogenerated
const MAX_SELECTION = 40;
// end of autogeneration

function printLegend()
{
	console.log('Node.JS SAMPLE APP');
  console.log('');

	console.log('Use UP and DOWN arrows to select animation and press ENTER.');
	console.log('');

	index = -1;

  if (selection == 0) {
    console.log('[*] Quit');
  } else {
    console.log('[ ] Quit');
  }

  var msg = '';
	for (var effect = 1; effect <= MAX_SELECTION; ++effect) {
    if (effect == selection) {
      msg += '[*]';
    } else {
      msg += '[ ]';
    }

    msg += ' Effect '+effect;

    if (effect % 5 == 0) {
      console.log(msg);
      msg = '';
    } else {
      msg += "\t\t";
    }
  }
  console.log(msg);


	console.log('');
  console.log('');
	console.log('['+selection+'] Press ENTER to play selection. ');
}

printLegend();

const readline = require('readline');

readline.emitKeypressEvents(process.stdin);
process.stdin.setRawMode(true);

process.stdin.on('keypress', (str, key) => {
  console.log(key)
  if (key.code == '[A') {
    if (selection > 0) {
      --selection;
    }
  }
  if (key.code == '[B') {
    if (selection < MAX_SELECTION) {
      ++selection;
    }
  }
  if (key.sequence == '\r') {
    console.log('ENTER');
  }
  printLegend();
})
